In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.naive_bayes import GaussianNB


In [ ]:
iris= datasets.load_iris()
X = iris.data
y = iris.target

print(iris.feature_names)
print(X[:5])
print(iris.target_names)
print(y[:5])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
['setosa' 'versicolor' 'virginica']
[0 0 0 0 0]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
dt_classifier = DecisionTreeClassifier()
dt_classifier.fit(X_train, y_train)
dt_predictions = dt_classifier.predict(X_test)

svm_classifier = SVC()
svm_classifier.fit(X_train, y_train)

svm_predictions = svm_classifier.predict(X_test)

In [ ]:
dt_accuracy= accuracy_score (y_test, dt_predictions)
dt_report= classification_report (y_test, dt_predictions)

print("Decision Tree Classifier:")
print(f"Accuracy: {dt_accuracy}")
print("Classification Report:")
print(dt_report)

svm_accuracy = accuracy_score(y_test, svm_predictions)
svm_report = classification_report(y_test, svm_predictions)

print("\nSupport Vector Machine (SVM) Classifier:")
print(f"Accuracy: {svm_accuracy}")
print("Classification Report:")
print(svm_report)

Decision Tree Classifier:
Accuracy: 1.0
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Support Vector Machine (SVM) Classifier:
Accuracy: 1.0
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



Task 1

In [ ]:

knn = KNeighborsClassifier(n_neighbors=3)


knn.fit(X_train, y_train)


knn_predictions = knn.predict(X_test)

# Calculate accuracy
knn_accuracy = accuracy_score(y_test, knn_predictions)
print("K-NN Accuracy: {:.2f}%".format(knn_accuracy * 100))


K-NN Accuracy: 100.00%


In [ ]:

random_forest = RandomForestClassifier(n_estimators=100, random_state=42)


random_forest.fit(X_train, y_train)


rf_predictions = random_forest.predict(X_test)

# Calculate accuracy
rf_accuracy = accuracy_score(y_test, rf_predictions)
print("Random Forest Accuracy: {:.2f}%".format(rf_accuracy * 100))


Random Forest Accuracy: 100.00%


In [ ]:

naive_bayes = GaussianNB()


naive_bayes.fit(X_train, y_train)


nb_predictions = naive_bayes.predict(X_test)

# Calculate accuracy
nb_accuracy = accuracy_score(y_test, nb_predictions)
print("Naive Bayes Accuracy: {:.2f}%".format(nb_accuracy * 100))


Naive Bayes Accuracy: 100.00%
